# Generated by Django 3.0 on 2019-12-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='age',
            field=models.SmallIntegerField(default=25),
        ),
    ]
